- scripts/dotfiles/create
Apparently `sed` command has different implementations depending on the platform, after a few tests in both Mac and GNU the only way I found to make it work is to actually replace said command.
More information can be found at:
https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux
On the other hand the `cp -r` command wasn't working for me either, looks like the trailing slash is needed (but I don't understand exactly why as it seems Ok without it).
> Make compatible dotfiles directory creation for all platforms

- scripts/self/install
Fixes: #5.
You can use the installer from my fork with the updated submodule reference as a temporary workaround till this is merged:
```bash
bash <(curl -s https://raw.githubusercontent.com/mglezsosa/dotly/dot-collision-installation-workaround/installer)
```
Dotly will be installed but you will get plenty of errors when sourcing your new dotfiles because of the collision, so the problem is bigger. Should we give more priority to our dotfiles, dotly and home binaries in the PATH env var by default? 
I've created a branch with this PR's change and setting this priority as well:
https://github.com/mglezsosa/dotly/blob/c595212bc1755c40b48ea08c83e545fe4d420c78/dotfiles_template/shell/_exports/exports.sh#L1
```bash
bash <(curl -s https://raw.githubusercontent.com/mglezsosa/dotly/more-priority-t …
```
> Force to use our 'dot' binary in the installation

- scripts/core/paths.sh
**Fix 'invalid mode' +111**
According to the website of [Finding Files](https://www.man7.org/linux/man-pages/man1/find.1.html)
`-perm +mode` This is no longer supported in **find**  
Should be use `-perm /mode`
`OS: Ubuntu 20`
> Fix 'invalid mode' in find -perm

- scripts/core/platform.sh
I use dotly in my daily work accross 3 different setups: a MacBook Pro, an Ubuntu laptop and a Desktop PC. The easiest way to make dotly work on my PC is using WSL. Creating my custom script I suddenly had the need to create a function to detect if dotly is running on WSL and I thought it could be useful for every dotly user that has faced the same issues.
1. Install dotly in WSL
2. Create a script that reads if its WSL and the ask for the path.
3. It should give the home path flawlessly
I have a single user system with a single WSL installed. I dont know if this implementation has any kind of trouble with another set of preconditions.
> Platform functions to detect if dotly is running in WSL

- scripts/mac/brew
Added `dot mac brew cleanup` subcommand to restore mac to the stored Brewfile packages or desired Brewfile provided. Useful because after some time you will probably test many packages for any reason and with these you will perform a full packages uninstall and cleanup.
> Feature: Added `dot mac brew cleanup` subcommand to restore mac

- scripts/core/output.sh
`output::question` core function did not run properly on macos under zsh due a reported bug (stackoverflow, at least) where "read -p" shows a "read: -p: no coprocess" error.
This is not showed when you install dotly because it is executed with bash shell instead of zsh.
> Fix: A known 'no coprocess' issue

- scripts/mac/defaults
Added subcommand "dot mac defaults import|export" to import and export mac settings to `$DOTFILES_PATH/os/mac/settings` folder the specified folder.
> Feature: Added feature to export and import defaults

- dotfiles_template/shell/aliases.sh
Because it makes sense access directly to your dotfiles from terminal.
> Feature: Added alias dotfiles

- .github/workflows/ci.yml
- installer
- scripts/self/utils/install.sh
Fix ".dotfiles/modules/dotly/scripts/self/utils/install.sh: line 7: DOTLY_ENV: unbound variable" while running the installer outside the CI server
I've set the `DOTLY_ENV` to `PROD` while running the installer as the documentation state understanding that the "production" environment for dotly would be this kind of scenario, but feel free to modify it to something better if you want to 😅
> Fix installer

- scripts/self/utils/install.sh
`mas` has added support for Apple Silicon: https://github.com/mas-cli/mas/pull/310
This would unlock being able to better dealing with Xcode issues like: https://github.com/CodelyTV/dotly/issues/89
> 🍎 Install mas even on Apple Silicon (arm64)

- scripts/package/dump
- scripts/package/import
- scripts/package/utils/dump.sh
[Volta](https://volta.sh/) is a JavaScript Tool Manager that helps to manage runtimes (node versions), package managers (npm, yarn), and also global modules.
It is similar to [nvm](https://github.com/nvm-sh/nvm) or [n](https://github.com/tj/n) but since it also takes responsibility for managing global modules, it can switch the node binary version under the scenes when you invoke a global module that depends on it. 
You installed [serve](https://github.com/vercel/serve) globally using `node@14.16.0`  then volta will call that specific version of node to run the `serve` command, even if you are using another node version at the moment.
Users that use Volta, don't use NPM to install global packages, so that's the reason why if the first is present, the latter is not used.
> Use Volta instead of NPM to dump global packages in case it is installed

- scripts/package/update_all
In case of having multiple Cargo dependencies installed such as:
```sh
{▸} ~ cargo install --list
docpars v0.2.0:
docpars
git-delta v0.6.0:
delta
```
The previous command was passing out multiple lines:
```sh
{▸} ~ cargo install --list | grep -E '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' '
docpars
git-delta
```
Because of these lines were being received by the very same `cargo install` command, it was failing:
```sh
{▸} ~ cargo install "$(cargo install --list | grep -E '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')"
Updating crates.io index
error: could not find `docpars
git-delta` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```
Now, it executes the `cargo install` multiple times, but at least do not produce crashes 😅
```sh
{▸} ~ cargo install --list | grep -E …
```
> [📦 rust] Fix crash while updating cargo dependencies

- scripts/package/update_all
Having pip3 installed does not imply having defined any dependencies for python.
This change avoids crashing while running the `up` command.
We were crashing because of the combination of `set -euo pipefail` with an empty input for the `grep -v '^\-e'` 🤟
> [🐍 python] Avoid crash in case of not having python dependencies

- shell/zsh/themes/prompt_codely_setup
Use stop icon `{▪}` for the prompt error status.
Red/green status colours may be indistinguishable for people with colour blindness, so this change helps to identify the status.
The icon represents that the command has **stopped** working, which is an analogy of stopping a video.
> Use {▪} icon for prompt error status

- scripts/self/install
Fixes `rust` installation when it is not possible to install from the package manager.
> Installer: fix install rust from sources

- scripts/package/dump
- scripts/package/import
- scripts/package/utils/dump.sh
Adds `Apt` packages support for `dot package dump` and `dot package import` commands.
The dump process only exports **manually** installed packages.
> Add Apt dump/import support

- shell/bash/completions/_dot
Fixed error that after all possible autocompletions that autocompletion can offer, show invalid arguments where were the context (which is the dotly scripts folder again).
Sample output of the error (wrong output and not error):
```
{◂} ~/.d/s/dotly dot package install
dotfiles  git       package   shell     symlinks
dotly     mac       self      surprise  ui
```
Which arguments are invalid because they're the context (second passed argument).
Rewrite of the `case` loop.
> Fix: Error in dot Bash autocompletion function

- scripts/git/commit
Not sure if you'll agree with this contribution, but I have to try 😬 
IMHO it is generally better to enable the commit gpg signature as a .gitconfig configuration instead of using the `-S` flag on each `git commit`, this is my rationale:
- Users using Dotly may or may not use GPG signature, this way we let them choose (otherwise the `gc` alias don't work unless you configure the key).
- If configured it always works, regardless of how you trigger the commit: `gc`, `git commit`, `dot git commit`, or any other alias.
- Conditional git configs are taken into account, so one can decide to use GPG or not depending on the repo, or parent folder. You can see an example of this in my dotfiles, where I [enable GPG for all my persona repos](https://github.com/d-asensio/dotfiles/blob/86975dfd66140f96 …
> Remove -S option that is forced per commit in the dot git commit command

- dotfiles_template/self-install-scripts/01-sample-script
- scripts/self/install
This feature allows any user to store files in their dotfiles that are executed in the installation process and this reduces the stuff that the user needs to do manually after recovering dotfiles.
I had some personal java configuration (and other stuff) to choose the version and some other programs needs to execute some symbolic links after installation this makes me easier how I recover my dotfiles reducing the manual steps I have to do.
Previous to this patch I did that work with annotations in the README.md file and executing all the annotated stuff manually.
To see how I use this feature: https://github.com/gtrabanco/dotfiles/tree/master/self-install-scripts
1. Create a bash script:
`echo "#!/usr/bin/env bash\necho \"I'm a teapot\"" >| …
> Feature: User scripts in installation process

- README.md
- dotfiles_template/README.md
Use git repository HEAD instead of any branch in the urls.
Added wget for recovery.
> Doc: Update installer and recovery urls

- scripts/git/find
I tried to use this script and I realized that it wasn't working. 
The error was: 
```sh
λ ~/.d/m/dotly on master ✗ dot git find "brew"
Invalid arguments.
Usage:
find "message to find"
```
After taking a look I saw that the parameter wasn't specified with the right syntax 🕵️
> Fix "git find" script parameter

- .gitmodules
- dotfiles_template/shell/zsh/.zimrc
- dotfiles_template/shell/zsh/.zshenv
- dotfiles_template/shell/zsh/.zshrc
- scripts/package/update_all
- scripts/self/install
- scripts/shell/zsh
Hola! 👋 Qué surpresa tan buena encontrar que a ustedes les gusta Zim y lo utilizan en su dotfiles y su curso de Zsh!
---
See changelog in https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md
Thanks a lot for chosing Zim as the Zsh framework of choice for your dotfiles and your courses!
I spotted a few points where the usage is not compatible with the changes since Zim 1.0.0 (released 2020-01-07):
* The zimfw repo is not intended to be cloned for daily use. You only need the zimfw.zsh file. And downloading it from https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh will always give you the latest released version of it.
* .zimrc should only contain module definitions, and it's not sourced anymore when the shell starts.
* `zhighlighters` is deprecated in favor of …
> Updates for Zim 1.x

- scripts/mac/defaults
defaults view_changed on clean install throws error.
----
hey el primer commando que ejecuto y pasa esto... 😁
> [FIX] {▪} ~ mac defaults view_changed failed on clean install 

- restorer
"dotly/restorer" fails on dotfiles backup because calls `create_dotfiles_dir` instead of `backup_dotfiles_dir`
> Fixed dotfiles folder backup on restorer

- scripts/package/src/dump.sh
`dot package dump` shows an error while dumping npm packages due to the change on default homebrew prefix on M1 Macs.
```
dot package
package dump
> Brew apps dumped on /Users/roi/.dotfiles/os/mac/brew/Brewfile
> Python apps dumped on /Users/roi/.dotfiles/langs/python/requirements.txt
ls: /usr/local/lib/node_modules: No such file or directory
```
Changing hardcoded path to use `$HOMEBREW_PREFIX` env var solves the problem
> fix: dump npm global packages

- scripts/core/platform.sh
- scripts/package/src/package_managers/gem.sh
- scripts/package/update_all
Why:
- Right now dotly tries to update all the Ruby dependencies from the Ruby installation that comes with macOS by default, but it fails in a lot of cases due to errors because the newer dependencies versions require an updated version of Ruby. Example:
>ERROR:  Error installing irb:
There are no versions of irb (= 1.7.4) compatible with your Ruby & RubyGems
irb requires Ruby version >= 2.7. The current ruby version is 2.6.10.210.
- Because these errors, dotly is not able to update these dependencies so it will indefinitely try to do so on each `up` command execution. This permanently increases the command execution time and adds noise to the command output.
- It is not recommended to update the default Ruby installation that comes with macOS because the [2.6 version is included for …
> feat: avoid updating default macOS Ruby dependencies

- scripts/package/src/package_managers/pip.sh
- We are actually checking if `platform::command_exists pip3` (not `platform::command_exists pip` before executing `pip::update_all`
- Inside the `pip::update_all` function we are already interacting with `pip3` in order to list outdated dependencies and show information about them
- It does not feel consistent to use `pip` while actually updating these dependencies
- It even throws an error every time we execute the `up` dotly command if we have not installed a Python environment further more the one which comes with macOS by default
> fix: use pip3 instead of pip
