CodelyTV/dotly

scripts/dotfiles/create
After talk with @rgomezcasas change perl command to sed again.
=> Use sed instead perl and maintain compatibility with MAC

dotfiles_template/README.md
Add all steps for restore your dotfiles in README.md generated in dotly installation.
* Install git
* Clone your dotfiles repository `git clone [your repository of dotfiles] $HOME/.dotfiles`
* Go to your dotfiles folder `cd $HOME/.dotfiles`
* Install git submodules `git submodule update --init --recursive`
* Install your dotfiles `$HOME/.dotfiles/modules/dotly/bin/dot self install`
Resolve #9
=> Restore your dotfiles documentation

installer
Le agregamos la "i" en la sentencia < dotfiles will be located in: > del instalador.
=> lost character

scripts/package/update_all
Improvement in update_all successfully execution message.
=> Improve update_all script message

dotfiles_template/symlinks/conf.yaml, scripts/self/install
=> Improve installation process

scripts/package/update_all
Just that. Cargo because I think you have forgotten to add it and deno because... Why not? Future is now.
=> Feature: Added cargo and deno to update_all dotly command

scripts/git/rm-file-history
Added git rm-file-history to delete a file across commits.
=> Feature: Added git rm-file-history

bin/pbcopy, bin/pbpaste
Credits: https://github.com/appaquet/dotfiles/blob/master/bin
This provides use of copy&paste in linux as macOS.
I am not sure if this is a good feature for dotly.
=> Feature: Added pbcopy and paste for Linux

.github/workflows/ci.yml, dotfiles_template/shell/exports.sh, scripts/self/utils/install.sh
Fixes #88 
Temporally workaround for #89
=> Improve the installation process on macOS

scripts/git/pretty-log
=> Fix git pretty-log when commit is a branch

scripts/package/dump, scripts/package/import, scripts/package/utils/dump.sh
Adds Snap packages support for `dot package dump` and `dot package import` commands.
=> Add Snap dump/import support

scripts/package/update_all
Automate the update of rust compiler because it is not updated with cargo update.
=> [Feature] Added rust compiler to update_all

shell/bash/themes/codely.sh, shell/zsh/themes/prompt_codely_setup
Done in order to be able to simplify the prompt in programs where you already know the path where you're at.
=> feat: add minimal mode for the terminal theme

dotfiles_template/README.md, dotfiles_template/install, easy-recovery, scripts/self/install, scripts/symlinks/apply
This adds a recover file to install your dotfiles.
Make simpler the restoration of your dotfiles
For me this works quite right. It will receive updates soon when more features were added. It would be nice make some more testing overall with Linux distros because the only test I did was in my intel osx.
If you remember this PR was open with Help needed. The problem was if any link fail in dotbot it was returning exit code error which made the program stop due to set option (`set -e`). It should be solved now.
=> [Feature]: Install your previous dotfiles from your dotfiles repository

scripts/package/update_all
Added Zimfw update in the update_all
=> Feature: Added ZIMFW update to update_all

scripts/git/pretty-diff, scripts/package/src/package_managers/composer.sh
=> Some improvements

dotfiles_template/shell/.inputrc, dotfiles_template/shell/bash/.bashrc, dotfiles_template/shell/zsh/.zshrc, shell/bash/themes/codely.sh
* Fix #178 
* Fix a issue that caused not to work right prompt when a theme was active
=> [Fix] Right prompt & Ctrl-L

dotfiles_template/shell/zsh/.zimrc
=> [Fix] #183

.editorconfig
Add a global configuration block to `.editorconfig`
Would it be a good idea to add an `.editorconfig` inside `dotfiles_template`?
=> feat(format): Add .editorconfig default options

README.md
Change WLS to WSL in README.md
=> doc(readme): fix typo in README.md

.gitignore, scripts/core/git.sh, scripts/git/changed-files
- I fixed an small typo error within the docs of the script.
- I added a new function into git core functions to allow to check if a branch exists.
- I parameterized the script receiving the branch name and verifying that it exists.
=> feat: allow to parameterize git branch for changed-files script

shell/bash/themes/codely.sh, shell/zsh/themes/prompt_codely_setup
=> feat: update theme to use the new branding
